### ISSUE TITLE
Name of the kind of diagram in README.md

### ISSUE THREAD

**Issue by mufasachan** [heyvaldemar/nextcloud-traefik-letsencrypt-docker-compose#2]
Hello, 

I am currently browsing repos with Traefik with `docker-compose.yml` to build my own homelab. Can you tell me the name of your kind of diagram you've done in your `README.md` please? I would like to make "big picture" diagram to sum my desired settings too. 

Have a nice day,
muffie.

**Comment by heyvaldemar** [comment]
hey @mufasachan,

I can recommend you [check possibilities](https://www.google.com/search?q=Creating+block+diagrams+from+docker-compose.yml) about how to automate the generation of a diagram for Docker Compose.

Additionally, you can try [Miro](https://miro.com/), [Lucichard](https://www.lucidchart.com) or [Diagrams.net](https://app.diagrams.net/).

You can reach me and other IT guys on [Discord](https://discord.gg/AJQGCCBcqf). It will be faster and more effective than here.

Have a great day!
