### ISSUE TITLE
Any cron is missing

### ISSUE THREAD

**Issue by Cotagge** [heyvaldemar/nextcloud-traefik-letsencrypt-docker-compose#3]
Hello, please is it possilble to add cron to your services? AJAX is not ok.

**Comment by heyvaldemar** [comment]
> Hello, please is it possilble to add cron to your services? AJAX is not ok.

hey, to which services? What do you want to achieve?

It will be easier to communicate on my Discord server https://discord.gg/AJQGCCBcqf
