### ISSUE TITLE
Your "trusted_proxies" setting is not correctly set, it should be an array of IP addresses

### ISSUE THREAD

**Issue by chrinats** [heyvaldemar/nextcloud-traefik-letsencrypt-docker-compose#4]
Hello,

Starting from nextcloud version 28.0.5 I can notice the following error:

> our "trusted_proxies" setting is not correctly set, it should be an array of IP addresses

I have tried to add the IP address of the traefik container into the trusted hosts inside config.php but that doesn't solve the issue. Any idea about the root cause?

Thanks for your help!

**Comment by heyvaldemar** [comment]
hey @chrinats, this seems to be related to [this](https://github.com/nextcloud/server/pull/44495).

Let's discuss this on our [Discord](https://discord.gg/AJQGCCBcqf) server; it'll be more convenient.
